async (page) => {
 const {fixture:f,observations:o}=globalThis.basketTest;
 const results=[];
 const ensure=(v,label)=>{if(!v)throw Error(label);results.push(label)};
 const clickTx=async name=>{const before=await page.evaluate(()=>window.__testWallet.sent.length);await page.getByRole('button',{name,exact:true}).click();await page.waitForFunction(n=>window.__testWallet.sent.length>n,before);await page.waitForFunction(()=>!document.querySelector('.wallet-status')?.textContent.includes('Checking transaction'));};
 await page.getByRole('link',{name:'Deposit',exact:true}).click();
 await page.getByLabel('Amount',{exact:true}).fill('10');await page.getByRole('button',{name:'Preview deposit',exact:true}).click();
 await page.getByRole('heading',{name:'Deposit preview'}).waitFor();
 ensure((await page.locator('.receipt').innerText()).includes('995 BASK'),'Deposit preview shows fee and received shares');
 await clickTx('2. Deposit');
 await page.getByLabel('Amount',{exact:true}).fill('999');await page.getByRole('button',{name:'Preview deposit',exact:true}).click();
 await page.getByText('This deposit exceeds the NAV cap. Stock at fault: ALFA.',{exact:true}).waitFor();results.push('DepositUnavailable decoded in plain words with stock');
 o.allowance=false;await page.getByRole('button',{name:'Refresh vault'}).click();await page.waitForFunction(()=>!document.querySelector('button.refresh').disabled);
 await page.getByLabel('Amount',{exact:true}).fill('10');await page.getByRole('button',{name:'Preview deposit',exact:true}).click();await page.getByRole('heading',{name:'Deposit preview'}).waitFor();
 await clickTx('1. Approve stock');
 ensure(await page.getByRole('button',{name:'2. Deposit',exact:true}).isDisabled(),'Deposit gated behind sufficient allowance');
 o.allowance=true;
 await page.getByRole('link',{name:'Redeem',exact:true}).click();await page.getByLabel('BASK amount').fill('10');await page.getByRole('button',{name:'Preview redemption',exact:true}).click();await page.getByRole('heading',{name:'Redemption preview'}).waitFor();
 ensure((await page.locator('.receipt').innerText()).includes('CHAR · retired'),'Redemption includes retired stock');
 await clickTx('Redeem BASK');
 const before=await page.evaluate(()=>window.__testWallet.sent.length);
 await page.getByLabel('Receiving address (optional)').fill('0x0000000000000000000000000000000000000000');await page.getByRole('button',{name:'Claim CHAR'}).click();
 await page.getByText('Enter a valid nonzero address.',{exact:true}).waitFor();ensure(await page.evaluate(()=>window.__testWallet.sent.length)===before,'Zero claim recipient rejected before wallet');
 await page.getByLabel('Receiving address (optional)').fill(f.user);await clickTx('Claim CHAR');
 await page.evaluate(owner=>window.__testWallet.change(owner,'0x1'),f.owner);
 ensure(await page.getByRole('button',{name:'Redeem BASK',exact:true}).isDisabled(),'Wrong-chain transaction disabled');
 await page.getByRole('button',{name:'Switch to chain 4663'}).click();ensure(await page.getByRole('button',{name:'Switch to chain 4663'}).count()===0,'Explicit switch chain works');
 await page.getByRole('link',{name:'Losses',exact:true}).click();await page.getByRole('button',{name:'Flag shortfall'}).waitFor();await clickTx('Flag shortfall');await clickTx('Recognise loss');
 await page.getByRole('link',{name:'Vault',exact:true}).click();
 o.failAggregate=true;o.failFeed=true;
 await page.getByRole('button',{name:'Refresh vault'}).click();await page.waitForFunction(()=>!document.querySelector('button.refresh').disabled);
 ensure(await page.locator('.stock-card').count()===3,'Aggregate failure recovers every stock individually');
 ensure((await page.locator('.stock-card').nth(1).innerText()).includes('unreadable'),'Failed feed marked unreadable while healthy stock remains priced');
 ensure((await page.locator('.stock-card').nth(0).innerText()).includes('$100'),'Healthy feed survives another failed read');
 ensure((await page.locator('.stats').innerText()).includes('unreadable'),'Partial held-price NAV is unreadable');
 o.failAggregate=false;o.failFeed=false;
 await page.getByRole('button',{name:'Refresh vault'}).click();await page.waitForFunction(()=>!document.querySelector('button.refresh').disabled);
 ensure(o.errors.length===0,'Every eth_call has 10M gas; heavy views never batched');
 return {results,sent:await page.evaluate(()=>window.__testWallet.sent),rpcCalls:o.calls.length};
}
