async (page) => {
 const {fixture:f,observations:o}=globalThis.basketTest;const results=[];
 const ensure=(v,label)=>{if(!v)throw Error(label);results.push(label)};
 const clickTx=async (locator)=>{const n=await page.evaluate(()=>window.__testWallet.sent.length);await locator.click();await page.waitForFunction(n=>window.__testWallet.sent.length>n,n);await page.waitForFunction(()=>!document.querySelector('.wallet-status')?.textContent.includes('Checking transaction'));};
 const panel=(title)=>page.locator('.panel').filter({has:page.getByRole('heading',{name:title,exact:true})});
 const submit=async(title,values={},confirm=false)=>{const p=panel(title);for(const [label,value] of Object.entries(values))await p.getByLabel(label,{exact:false}).fill(value);if(confirm)await p.getByRole('checkbox').check();await clickTx(p.getByRole('button',{exact:true}));};
 await page.getByRole('link',{name:'Owner',exact:true}).click();
 await page.getByRole('button',{name:'Execute',exact:true}).waitFor();
 ensure(await page.getByRole('button',{name:'Execute',exact:true}).count()===1,'Only successful execution simulation shows Execute');
 ensure((await page.locator('main').innerText()).includes('The seven-day proposal delay has not ended.'),'Failed execute simulation shows reason');
 await submit('New stock',{'Stock Token address':f.assets[0].token,'New feed address':f.assets[0].feed});
 await submit('Replacement feed',{'New feed address':f.assets[1].feed});
 await submit('Re-centre a price band');await submit('Reopen a stock');await submit('Retire a closed stock',{},true);
 await submit('New guardian',{'New guardian address':f.user});await submit('Raise the NAV cap',{'New NAV cap (USD)':'2000000'});
 await clickTx(page.getByRole('button',{name:'Execute',exact:true}));
 await clickTx(page.getByRole('button',{name:'Cancel proposal',exact:true}).first());
 await page.getByRole('button',{name:'Next proposal page'}).click();await page.getByRole('heading',{name:'No pending proposals on this page'}).waitFor();results.push('Pending proposals pagination uses historical IDs');
 await page.getByRole('button',{name:'Previous proposal page'}).click();await page.getByRole('button',{name:'Execute',exact:true}).waitFor();
 await submit('Close a stock');await clickTx(page.getByRole('button',{name:'Pause deposits',exact:true}));await clickTx(page.getByRole('button',{name:'Unpause deposits',exact:true}));
 await submit('Lower the NAV cap',{'Lower NAV cap (USD)':'500000'});
 await submit('Set the fee recipient',{'Fee recipient address':f.user},true);
 await submit('Transfer ownership',{'New owner address':f.user});
 await page.evaluate(p=>window.__testWallet.change(p,'0x1237'),f.pending);
 await clickTx(page.getByRole('button',{name:'Accept ownership',exact:true}));
 await page.evaluate(p=>window.__testWallet.change(p,'0x1237'),f.guardian);
 ensure(await page.getByRole('button',{name:'Unpause deposits',exact:true}).isDisabled(),'Guardian cannot unpause');
 ensure(!(await page.getByRole('button',{name:'Pause deposits',exact:true}).isDisabled()),'Guardian can pause');
 ensure(await page.getByRole('button',{name:'Cancel proposal',exact:true}).nth(1).isDisabled(),'Guardian cannot cancel guardian replacement');
 ensure(!(await page.getByRole('button',{name:'Cancel proposal',exact:true}).first().isDisabled()),'Guardian can cancel other proposals');
 await page.evaluate(p=>window.__testWallet.change(p,'0x1237'),f.user);
 ensure(await page.getByRole('heading',{name:'Set the fee recipient',exact:true}).isVisible(),'Non-owner sees owner controls');
 ensure(await page.getByRole('button',{name:'Set fee recipient',exact:true}).isDisabled(),'Non-owner blocked from owner action');
 await page.evaluate(p=>window.__testWallet.change(p,'0x1237'),f.owner);
 const genesis=Object.keys(f.calls).find(k=>k.endsWith(':0x4421d5f5'));f.calls[genesis]='0x'+'0'.repeat(64);
 await page.getByRole('button',{name:'Refresh vault'}).click();await page.waitForFunction(()=>!document.querySelector('button.refresh').disabled);
 await submit('List the launch basket',{'Stock Token and feed pairs':['ALFA','BRAV','CHAR'].map((sym,i)=>`${sym} ${f.assets[i].token} ${f.assets[i].feed}`).join('\n')});
 await submit('Finalize genesis',{},true);
 await page.getByLabel('Receiving address (optional)').fill('');await clickTx(page.getByRole('button',{name:'Claim CHAR'}));
 ensure(o.errors.length===0,'All owner reads and simulations preserve gas limits');
 return {results,sent:await page.evaluate(()=>window.__testWallet.sent)};
}
